name: run-test

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "*"
    tags:
      - "*"
    paths-ignore:
      - "**.md"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to vrelease
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -t vrelease .

      - name: Run test
        run: |
          docker run --rm vrelease -h
          docker run --rm vrelease -v
